### ISSUE TITLE
error 204 on sanctrum request

### ISSUE THREAD

**Issue by YnievesDotNet** [NiclasTimmeDev/laravel-nextjs-starter#31]
I tried of request csrf-cookie and get error 204...

![photo_2021-04-09 23 48 30](https://user-images.githubusercontent.com/1451485/114257460-2def5f00-998e-11eb-8b67-ab4e1997f7f0.jpeg)

Thanks

**Comment by niclas-timm** [comment]
Any status code of 2xx is not an error but a success. 204 means "no content" and is the expected response of the api.
